language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

env:
  - TYPE=mysql
  - TYPE=pgsql

install:
  - composer selfupdate
  - composer install

before_script:
  - if [[ "$TYPE" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS b8_test;" -uroot; fi
  - if [[ "$TYPE" == "pgsql" ]]; then psql -c 'create database b8_test;' -U postgres; fi

script:
  - vendor/bin/phpunit --configuration phpunit.$TYPE.xml --coverage-text

notifications:
  email:
    recipients:
      - poisoncorpsee@gmail.com

    on_success: always
    on_failure: always
