b8:
    database:
        servers:
            read: [{ host: localhost }]
            write: [{ host: localhost }]
        type: mysql
        name: php-censor
        username: root
        password: qweewq
php-censor:
    language: en
    per_page: 10
    url: 'http://php-censor.loc'
    queue:
        use_queue: false
        host: null
        name: null
        lifetime: 600
    email_settings:
        from_address: no-reply@php-censor.local
        smtp_address: null
        smtp_port: null
        smtp_username: null
        smtp_password: null
        smtp_encryption: false
    github:
        token: null
        comments:
            commit: false
            pull_request: false
    build:
        remove_builds: true
    security:
        disable_auth: false
        default_user_id: 1
        auth_providers:
            internal: { type: internal }
